# [Python NumPy Basic](https://www.w3schools.com/python/numpy_intro.asp)

In [6]:
# import numpy as an alias - np
import numpy as np

In [8]:
print(np.__version__)

1.18.5


## Create a NumPy ndarray Object

In [16]:
# use a list, tuple or any array-like object into array() to create an array
arr = np.array([1,2,3])

In [17]:
print(arr)

[1 2 3]


In [15]:
print(type(arr))

<class 'numpy.ndarray'>


## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

#### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [24]:
a = np.array(2)

#### 2-D Array

In [28]:
b = np.array([['A',2,3],['B', 3, 4]])

In [29]:
print(b)

[['A' '2' '3']
 ['B' '3' '4']]


In [35]:
b2 = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])

In [36]:
print(b2)

[['A' '2' '3']
 ['B' '3' '4']
 ['C' '2' '1']]


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [51]:
# Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6:

c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

## Check Number of Dimensions

In [56]:
print(a.ndim)
print(b.ndim)
print(b2.ndim)

print(c.ndim)

0
2
2
3


#### Higher dimension

In [75]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

# access element
print(arr[0][0][0][0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
[1 2 3 4]


## Access elements

#### Access a row

In [324]:
# access row 2 on 1 dim
arr = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])
row2 = arr[1]

print(arr.shape)
print(arr.ndim)

print(row2.shape)
print(row2)

(3, 3)
2
(3,)
['B' '3' '4']


#### Access a column

In [321]:
#  col2 in all arrays

arr = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])
col2_all = arr[:,1]   #. all rows, 2nd cols

print(col2_all)

['2' '3' '2']


In [87]:
# Concatenation - same types only

arr = np.array([1, 2, 3, 4])

print(arr[0]+arr[2])
print(arr)

4
[1 2 3 4]


In [181]:
# Access 2-D

b2 = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])

print(b2[0])

print(f'row1, 2nd element is {b2[0][1]}')
print(b2[0,2])      #. same as b2[0][1] dim/row, col

print(b2[2,0])      #. 3rd dimension, 1st element.


# concatenation
print(b2[0,0]+b2[1,0]+b2[2,0])


# negative indexing
print(b2[-1, -1])

['A' '2' '3']
row1, 2nd element is 2
3
C
ABC
1


## Slicing
We can also define the step, like this: [start:end:step]

#### Access arrays

In [178]:
# access all for 2-D

arr = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])
print(arr[:,:])   #. [row, col]

[['A' '2' '3']
 ['B' '3' '4']
 ['C' '2' '1']]


In [328]:
# access 2nd and 3rd cols among rows

arr = np.array([['A',2,3],['B', 3, 4],['C', 2, 1]])

print(arr[:,1:3])

[['2' '3']
 ['3' '4']
 ['2' '1']]


In [177]:
# access the 2nd array from a 3-D array

arr = np.array([[['A',2,3],['B', 3, 4]],[['C', 2, 1],['D', 4,5]]])

print(arr[1,:])
print(arr.ndim)

[['C' '2' '1']
 ['D' '4' '5']]
3


In [95]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

# From the second element, slice elements from index 1 to index 4 (not included):
print(arr[1, 1:4])

[7 8 9]


#### Slice both elements, will return a 2-D array

In [96]:
# slice index 1 to 4 from both dimensions/elements

print(arr[1:4, 1:4])

[[7 8 9]]


## [Data Type of an Array](https://www.w3schools.com/python/numpy_data_types.asp)

In [102]:
# create an array with a defined string type

arr = np.array([1, 2, 3, 4], dtype = 'S')     #string
print(arr.dtype)

|S1


## Convert Data Type on existing arrays

The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [112]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')     #. convert float to integer type

print(arr.dtype)
print(newarr)
print(newarr.dtype)

float64
[1 2 3]
int32


In [109]:
# use int

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [113]:
# change to boolean

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


## Copy and View

- copy and a view of an array is that the copy is a new array 
- view is just a view of the original array.

In [115]:
# The copy SHOULD NOT be affected by the changes made to the original array.

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr) 
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [117]:
# The view SHOULD be affected by the changes made to the original array.


arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr) 
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [119]:
# The original array SHOULD be affected by the changes made to the view.

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


## Check if Array owns it's data

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [127]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()
y[0] = 5
arr[0] = 45

print(x.base)    #. own its own data. self is the base
print(y.base)
print(y)
print(arr)

None
[45  2  3  4  5]
[45  2  3  4  5]
[45  2  3  4  5]


## Shape (tuple)

- The shape of an array is the number of elements in each dimension.


In [128]:
# shape (2,4) = 2 by 4 matrix = 2 dimentions with 4 elements in each.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [136]:
# x,y,z
arr = np.array([[[1, 2, 3, 4],[2,5,5,3]]])

print(arr)
print('shape of array :', arr.shape)

[[[1 2 3 4]
  [2 5 5 3]]]
shape of array : (1, 2, 4)


## Reshaping
- change the shape of an array
- change dimension or number of elements in each dimension

In [142]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)    #. 2x6 total elements = 12
newarr2 = arr.reshape(4, 3)   #. 4x3

print(newarr)
print(newarr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### 1-D to 3-D

In [143]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [150]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)    #. it's a view

[1 2 3 4 5 6 7 8]


## Unknown Dimension

You do not have to specify all exact numbers for the dimensions in the reshape method.

- Pass -1 as the value, and NumPy will calculate this number for you.
- -1 can be placed in any positional order.

In [155]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, -1, 2)   #. use -1 to auto calculate the last dimension

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flatten the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [187]:
arr_3D = np.array([[['A',2,3],['B', 3, 4]],[['C', 2, 1],['D', 4,5]]])

newarr = arr_3D.reshape(-1)

print(newarr)

['A' '2' '3' 'B' '3' '4' 'C' '2' '1' 'D' '4' '5']


## Iterate an array

In [212]:
arr_3D = np.array([[['A',2,3],['B', 3, 4]],[['C', 2, 1],['D', 4,5]]])

for x in arr_3D:
    print(x)
    
# print(arr_3D.ndim)

[['A' '2' '3']
 ['B' '3' '4']]
[['C' '2' '1']
 ['D' '4' '5']]


In [201]:
# alternative way to view row 0, row 1

for x in range(2):
    print(arr_3D[x])

[['A' '2' '3']
 ['B' '3' '4']]
[['C' '2' '1']
 ['D' '4' '5']]


#### Iterate each scalar element of the 2-D array

In [209]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# for x in arr:
#     print(x)
    
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


#### Iterating all elements Using nditer()
- useful for high dimensionality

In [214]:
arr_3D = np.array([[['A',2,3],['B', 3, 4]],[['C', 2, 1],['D', 4,5]]])

for x in np.nditer(arr_3D):
    print(x)

A
2
3
B
3
4
C
2
1
D
4
5


### Iterating Array With Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [221]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


### Iterating With Different Step Size


In [228]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Iterate through every scalar element of the 2D array skipping 1 element. ::
for x in np.nditer(arr[:, ::2]):
  print(x)

print()

# Iterate index 0-2 elements/cols for every arrays/row.
for x in np.nditer(arr[:, :2]):
  print(x)

1
3
5
7

1
2
5
6


## 

## Enumerated Iteration Using ndenumerate()


In [229]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [233]:
for x, y in np.ndenumerate(arr):
    print(x,y)

(0,) 1
(1,) 2
(2,) 3


In [239]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.ndenumerate(arr):
  print(x)

print(x)

((0, 0), 1)
((0, 1), 2)
((0, 2), 3)
((0, 3), 4)
((1, 0), 5)
((1, 1), 6)
((1, 2), 7)
((1, 3), 8)
((1, 3), 8)


In [238]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

print(x)
print(idx)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
8
(1, 3)


## Join Arrays
> concatenate()

In [242]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


#### Join two 2-D arrays along rows (axis=1)
- axis=0 => combined by rows (x)
- axis = 1 ==> combined by cols (y)

In [269]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)   #. axis = 1 ==> combined by col(y) 

print(arr)
print(arr.shape)

[[1 2 5 6]
 [3 4 7 8]]
(2, 4)


#### Join along columns (axis=0)

In [268]:
# without specifying axis, 

arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])

arr = np.concatenate((arr1, arr2))   #. axis = 0(= x = row)

print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [2 5]
 [5 6]
 [7 8]
 [5 6]]
(6, 2)


In [298]:
arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])
arr3 = np.array([[7, 6], [9, 8],[4,7]])


arr = np.concatenate((arr1, arr2, arr3), axis=1)   

print(arr)
print(arr.shape)

[[1 2 5 6 7 6]
 [3 4 7 8 9 8]
 [2 5 5 6 4 7]]
(3, 6)


#### Stack Join
- same as concatenate with axis=1 but "stacked"

In [290]:
arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])
arr3 = np.array([[7, 6], [9, 8],[4,7]])

arr = np.stack((arr1, arr2, arr3), axis=1)   

print(arr)
print(arr.shape)

[[[1 2]
  [5 6]
  [7 6]]

 [[3 4]
  [7 8]
  [9 8]]

 [[2 5]
  [5 6]
  [4 7]]]
(3, 3, 2)


#### Stack along rows
> hstack()

In [308]:
arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])
arr3 = np.array([[7, 6], [9, 8],[4,7]])

arr = np.hstack((arr1, arr2, arr3))

print(arr)
print(arr.shape)

[[1 2 5 6 7 6]
 [3 4 7 8 9 8]
 [2 5 5 6 4 7]]
(3, 6)


#### Stack along columns
> vstack()

In [287]:
arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])
arr3 = np.array([[7, 6], [9, 8],[4,7]])

arr = np.vstack((arr1, arr2, arr3))

print(arr)
print(arr.shape)

[[1 2]
 [3 4]
 [2 5]
 [5 6]
 [7 8]
 [5 6]
 [7 6]
 [9 8]
 [4 7]]
(9, 2)


#### Stack along Height (depth)
> dstack()

In [310]:
arr1 = np.array([[1, 2], [3, 4],[2,5]])
arr2 = np.array([[5, 6], [7, 8],[5,6]])
arr3 = np.array([[7, 6], [9, 8],[4,7]])

arr = np.dstack((arr1, arr2, arr3))

print(arr)
print(arr.shape)

[[[1 5 7]
  [2 6 6]]

 [[3 7 9]
  [4 8 8]]

 [[2 5 4]
  [5 6 7]]]
(3, 2, 3)


## Split Array
> array_split()
- If the array has less elements than required, it will adjust from the end accordingly.



In [313]:
# Split the array in 3 parts
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [303]:
# Split into 4 parts

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


#### split()
when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

In [341]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


#### Split 2-D array
- split into n 2-D arrays list

In [338]:
# split into 3 2-D arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

print(type(newarr))

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
<class 'list'>


#### Split based along rows and cols
- axis = 0 (along cols)
- axis = 1 (along rows)

In [358]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f'original:\n\n{arr}\n')

# split into 3 arrays along rows (axis=1)

newarr = np.array_split(arr, 3, axis = 1)
print(newarr)

original:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [362]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f'original:\n\n{arr}\n')

# split into 3 arrays along the cols (axis=0)

newarr = np.array_split(arr, 3, axis = 0)
print(newarr)

original:

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


#### hsplit()
- opposite of hstack()

In [369]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f'{arr}\n')

newarr = np.hsplit(arr, 3)

print(newarr[0])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


#### vsplit()

In [377]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f'{arr}\n')

newarr = np.vsplit(arr, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


#### dsplit() for 3-D array
- return 3-D arrays x n

In [408]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(c.shape)   #. # arrays, # of rows, # of cols
print(c)

(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [399]:
# split into 3 3-D arrays based on element

newarr = np.dsplit(c,3)  #. array[1,4,1,4], array[2,5,2,5], array[3,6,3,6]
print(newarr)

[array([[[1],
        [4]],

       [[1],
        [4]]]), array([[[2],
        [5]],

       [[2],
        [5]]]), array([[[3],
        [6]],

       [[3],
        [6]]])]


In [409]:
# Flaten arrays from 3-D to 1-D

print(c.reshape(-1))

[1 2 3 4 5 6 1 2 3 4 5 6]


## Search
-  return the indexes that get a match
> where()

In [412]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

# the value 4 is present at index 3, 5, and 6.

(array([3, 5, 6]),)


In [413]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)   #. odd numbers

print(x)

(array([0, 2, 4, 6]),)


#### Search Sorted

- The searchsorted() method is assumed to be used on sorted arrays.



In [415]:
# Find the indexes where the value 7 should be inserted

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


#### Search from right-side
> side='right'

In [416]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


#### Multiple Values
To search for more than one value, use an array with the specified values.



In [427]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])


# The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.
x = np.searchsorted(arr, [2,4,6])
print(x)

# place value 8 in index 4 to maintain the order.
y = np.searchsorted(arr, [8])
print(y)


[1 2 3]
[4]


## Sort

In [428]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [429]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [430]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


#### Sort a 2-D Array

- both arrays will be sorted

In [440]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

print(newarr)

[[2 3 4]
 [0 1 5]]
[41 43]


## Filter Arrays
- In NumPy, you filter an array using a boolean index list.


In [443]:
# Create an array from the elements on index 0 and 2:
arr = np.array([41, 42, 43, 44])

x = [True, False, False, True]    #. return Ture values only
newarr = arr[x]

print(newarr)

[41 44]


#### Filter 2-D array *

In [483]:
arr = np.array([[41, 42, 43, 44],[55, 42, 43, 77]])
print(arr)

x = [True, False, False, True]


[[41 42 43 44]
 [55 42 43 77]]


In [484]:
# filter all rows based on x logic
print(arr[:,x])

[[41 44]
 [55 77]]


In [486]:
# filter 2nd row only based on x logic
print(arr[1][x])

[55 77]


#### Create Filter Array *

In [488]:
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]    #. neaarr = array[Boolean Filter]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [493]:
# Ex. 
# Create a filter array that will return only even elements from the original array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = []

for e in arr:
    if e % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
print(filter_arr)
print(arr[filter_arr])


[False, True, False, True, False, True, False]
[2 4 6]


#### √ Creating Filter Directly From Array

In [495]:
# Create a filter array that will return only values higher than 42:

arr = np.array([41, 42, 43, 44])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True]
[42 44]


#### Create Filter from 2-D Array *

In [499]:
arr = np.array([[41, 42, 43, 44],[55, 42, 43, 77]])

filter_arr = arr[:] > 43

# print Boolean Filter
print(filter_arr)

print(arr[filter_arr])

[[False False False  True]
 [ True False False  True]]
[44 55 77]


## [Numpy Random Numbers](https://www.w3schools.com/python/numpy_random.asp)

- If there is a program to generate random number it can be predicted, thus it is not truly random.
- Random numbers generated through a generation algorithm are called pseudo random.

> random()

1. random numbers
2. distributions

In [502]:
from numpy import random

In [516]:
# Generate a random integer from 0 to 100 [0,100):

x = random.randint(100)  #. 100 is excluded
print(x)

83


In [509]:
# Generate a float

x = random.rand(1)
print(x)

[0.29618558]


### Generate Random Array

- randint(n, size=())

#### 1-D Array

In [518]:
# 1-D array [0,2)

x=random.randint(2, size=(5))
print(x)

[0 1 0 1 1]


#### 2-D Array

In [521]:
# int size = (row, col)

x=random.randint(2, size=(2,5))
print(x)

[[1 0 1 1 0]
 [1 1 1 1 0]]


In [522]:
# float

x = random.rand(3, 5)

print(x)

[[0.99751019 0.26707209 0.12495624 0.37527569 0.94372834]
 [0.74831352 0.4360822  0.52462483 0.68698503 0.49277062]
 [0.89585062 0.21697812 0.9430117  0.88353447 0.86289836]]


### Generate Random Number From Array
> choice(array, size=())

- The choice() method also allows you to return an array of values.
- Add a size parameter to specify the shape of the array.

#### Generate a number

In [526]:
# select among a tuple
x = random.choice((3, 5, 7, 9))

# select among a list/1-D array
y = random.choice([2,3,4,5])

print(x)
print(y)

7
5


#### Generate a multi-dimensional array

In [530]:
# generate a 3x5 array

x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[9 9 5 3 7]
 [5 9 3 7 7]
 [9 7 9 5 3]]


In [532]:
# generate a 3D array (3 arrays, 2 by 5)

x = random.choice([3, 5, 7, 9], size=(3, 2, 5))
print(x)

[[[9 7 9 9 5]
  [3 3 7 3 9]]

 [[9 7 7 3 7]
  [5 5 7 7 9]]

 [[3 3 3 9 5]
  [9 3 7 9 5]]]
